<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <!-- Test packages -->
    <PackageReference Include="AutoFixture.AutoMoq" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" />
    <PackageReference Include="Grpc.AspNetCore.Web" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Net.Client.Web" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Respawn" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Peerly.Core.Api\Peerly.Core.Api.csproj" />
    <ProjectReference Include="..\..\src\Peerly.Core.Hosting\Peerly.Core.Hosting.csproj" />
  </ItemGroup>
</Project>
